"""
`tools/list` JSON Schema, translated for Gemini, with a report of what it cost.

The schemas are never hand-written here. They come from the MCP server's own
`tools/list` -- the same objects that generate tool mode's forms and that the
Anthropic path passes through untouched -- so a `Field(description=...)` edited
in `server.py` moves every surface at once. This module only re-dialects them.

Two dialects exist, and `FunctionDeclaration` takes one or the other:

  * `parameters_json_schema` -- standard JSON Schema. Tried first, because our
    schemas are already that and the translation is then close to identity.
  * `parameters` -- an OpenAPI 3.0 subset. The fallback. Its keyword set is
    genuinely smaller, and `drops()` below says exactly which of OUR keywords
    fall outside it rather than leaving that to be discovered at runtime.

The point of reporting rather than silently dropping: a constraint the model is
not told about does not disappear from the system. The MCP server still holds
it -- `bucket_size` is bounded by pydantic at the schema layer and by
`require_bucket_size()` in the tool body -- so a value the dialect failed to
forbid comes back as a refusal card with the server's own reasoning attached.
That is a visible failure, which is the point, but it is only honest if someone
knows in advance which constraints have been demoted to it.
"""

from __future__ import annotations

from typing import Any

# Every keyword `types.Schema` carries in google-genai, in JSON Schema spelling.
# Read off `types.Schema.model_fields`, not off the prose documentation, and
# asserted against the installed SDK by a test so a version bump that widens or
# narrows the dialect fails here rather than in a deployment.
OPENAPI_SUBSET = frozenset({
    "additionalProperties", "$defs", "$ref", "anyOf", "default", "description",
    "enum", "example", "format", "items", "maxItems", "maxLength",
    "maxProperties", "maximum", "minItems", "minLength", "minProperties",
    "minimum", "nullable", "pattern", "properties", "propertyOrdering",
    "required", "title", "type",
})

# Structural keys, not constraints: they carry other schemas and are walked
# rather than compared.
_CONTAINERS = frozenset({"properties", "items", "anyOf", "$defs"})


def drops(schema: dict) -> list[tuple[str, str]]:
    """
    [(json pointer-ish path, keyword)] this schema would lose in the subset.

    Paths are readable rather than RFC 6901 -- they are for a log line and a
    test failure, not for a resolver.
    """
    lost: list[tuple[str, str]] = []

    def walk(node: Any, path: str) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "properties" and isinstance(value, dict):
                    for name, sub in value.items():
                        walk(sub, f"{path}/{name}")
                    continue
                if key in _CONTAINERS:
                    walk(value, path)
                    continue
                if key not in OPENAPI_SUBSET:
                    lost.append((path or "/", key))
        elif isinstance(node, list):
            for item in node:
                walk(item, path)

    walk(schema, "")
    return lost


def to_openapi_subset(schema: dict) -> dict:
    """
    The fallback dialect: drop what it cannot express, and idiomatise the rest.

    Two rewrites rather than pass-throughs:

    * `anyOf: [{type: X}, {type: "null"}]` becomes the inner type with
      `nullable: true`. Gemini's `Type` enum does have NULL, so the literal
      form is representable, but `nullable` is the form its function-calling
      path actually honours -- and every optional parameter in this server's
      surface is exactly that shape, generated by pydantic from `X | None`.
    * `additionalProperties: false` is kept where the field exists but is not
      relied on; the server rejects unknown parameters regardless.
    """
    return _convert(schema)


def _convert(node: Any) -> Any:
    if isinstance(node, list):
        return [_convert(v) for v in node]
    if not isinstance(node, dict):
        return node

    nullable = _nullable_pair(node)
    if nullable is not None:
        inner = dict(nullable)
        inner["nullable"] = True
        for key, value in node.items():
            if key != "anyOf":
                inner.setdefault(key, value)
        node = inner

    out: dict[str, Any] = {}
    for key, value in node.items():
        if key == "properties" and isinstance(value, dict):
            out[key] = {name: _convert(sub) for name, sub in value.items()}
        elif key in _CONTAINERS:
            out[key] = _convert(value)
        elif key in OPENAPI_SUBSET:
            out[key] = value
        # else: dropped, and `drops()` already said so.
    return out


def _nullable_pair(node: dict) -> dict | None:
    """The non-null branch of an `anyOf` that is exactly [T, null], else None."""
    branches = node.get("anyOf")
    if not isinstance(branches, list) or len(branches) != 2:
        return None
    nulls = [b for b in branches if isinstance(b, dict) and b.get("type") == "null"]
    others = [b for b in branches if isinstance(b, dict) and b.get("type") != "null"]
    if len(nulls) == 1 and len(others) == 1:
        return others[0]
    return None


def declarations(tools: list[dict], *, dialect: str) -> tuple[list[dict], list[tuple[str, str, str]]]:
    """
    (function declarations, losses) for the whole tool surface.

    `dialect` is "json_schema" or "openapi". Losses are
    (tool name, parameter path, keyword) and are empty by construction on the
    json_schema path -- which is the claim the live API has to confirm, so the
    caller logs the count either way rather than assuming.
    """
    if dialect not in ("json_schema", "openapi"):
        raise ValueError(f"unknown dialect {dialect!r}")

    decls: list[dict] = []
    losses: list[tuple[str, str, str]] = []
    for tool in tools:
        schema = tool.get("input_schema") or {"type": "object", "properties": {}}
        if dialect == "json_schema":
            params = {"parameters_json_schema": schema}
        else:
            for path, keyword in drops(schema):
                losses.append((tool["name"], path, keyword))
            params = {"parameters": to_openapi_subset(schema)}
        decls.append({
            "name": tool["name"],
            "description": tool["description"],
            **params,
        })
    return decls, losses


def describe_losses(losses: list[tuple[str, str, str]]) -> str:
    """One line per lost keyword, for the startup log."""
    if not losses:
        return "no schema keyword was dropped"
    lines = [f"{len(losses)} schema keyword(s) dropped for gemini:"]
    for tool, path, keyword in losses:
        lines.append(
            f"  {tool}{path}: {keyword} — still enforced by the server, so a "
            f"value it would have forbidden returns a refusal card instead"
        )
    return "\n".join(lines)
